2025-01-19 12:04:02,600 INFO    Thread-10 :11544 [wandb_setup.py:_flush():71] setting env: {'project': 'Ablation_LLMs', 'entity': 'maestria-julian', 'root_dir': '/home/julian/CATALOG', 'sweep_id': 'u7f4vnfw', 'run_id': 'vvizkay0', 'sweep_param_path': '/home/julian/CATALOG/wandb/sweep-u7f4vnfw/config-vvizkay0.yaml'}
2025-01-19 12:04:02,600 INFO    Thread-10 :11544 [wandb_setup.py:_flush():71] setting login settings: {}
2025-01-19 12:04:02,600 INFO    Thread-10 :11544 [wandb_init.py:_log_setup():357] Logging user logs to /home/julian/CATALOG/wandb/run-20250119_120402-vvizkay0/logs/debug.log
2025-01-19 12:04:02,600 INFO    Thread-10 :11544 [wandb_init.py:_log_setup():358] Logging internal logs to /home/julian/CATALOG/wandb/run-20250119_120402-vvizkay0/logs/debug-internal.log
2025-01-19 12:04:02,601 INFO    Thread-10 :11544 [wandb_init.py:init():390] calling init triggers
2025-01-19 12:04:02,601 INFO    Thread-10 :11544 [wandb_init.py:init():395] wandb.init called with sweep_config: {'batch_size': 58, 'dropout': 0.3567594194973879, 'hidden_dim': 749, 'lr': 0.07558168040294555, 'momentum': 0.8325690919707244, 'num_epochs': 125, 'num_layers': 1, 'opt': 'sgd', 'patience': 10, 't': 0.01, 'weight_Clip': 0.7614233219649424}
config: {}
2025-01-19 12:04:02,601 INFO    Thread-10 :11544 [wandb_init.py:init():435] starting backend
2025-01-19 12:04:02,601 INFO    Thread-10 :11544 [backend.py:_multiprocessing_setup():94] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-19 12:04:02,617 INFO    Thread-10 :11544 [backend.py:ensure_launched():198] starting backend process...
2025-01-19 12:04:02,623 INFO    Thread-10 :11544 [backend.py:ensure_launched():203] started backend process with pid: 11592
2025-01-19 12:04:02,626 INFO    Thread-10 :11544 [wandb_init.py:init():444] backend started and connected
2025-01-19 12:04:02,630 INFO    Thread-10 :11544 [wandb_run.py:_config_callback():911] config_cb None None {'batch_size': 58, 'dropout': 0.3567594194973879, 'hidden_dim': 749, 'lr': 0.07558168040294555, 'momentum': 0.8325690919707244, 'num_epochs': 125, 'num_layers': 1, 'opt': 'sgd', 'patience': 10, 't': 0.01, 'weight_Clip': 0.7614233219649424}
2025-01-19 12:04:02,631 INFO    Thread-10 :11544 [wandb_init.py:init():503] updated telemetry
2025-01-19 12:04:02,648 INFO    Thread-10 :11544 [wandb_init.py:init():533] communicating current version
2025-01-19 12:04:04,535 INFO    Thread-10 :11544 [wandb_init.py:init():538] got version response upgrade_message: "wandb version 0.19.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-01-19 12:04:04,536 INFO    Thread-10 :11544 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2025-01-19 12:04:04,934 INFO    Thread-10 :11544 [wandb_init.py:init():576] starting run threads in backend
2025-01-19 12:04:06,323 INFO    Thread-10 :11544 [wandb_run.py:_console_start():1693] atexit reg
2025-01-19 12:04:06,323 INFO    Thread-10 :11544 [wandb_run.py:_redirect():1567] redirect: SettingsConsole.REDIRECT
2025-01-19 12:04:06,324 INFO    Thread-10 :11544 [wandb_run.py:_redirect():1572] Redirecting console.
2025-01-19 12:04:06,324 ERROR   Thread-10 :11544 [wandb_run.py:_redirect():1631] Failed to redirect.
Traceback (most recent call last):
  File "/home/julian/miniconda3/envs/CATALOG/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1624, in _redirect
    out_redir.install()
  File "/home/julian/miniconda3/envs/CATALOG/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/julian/miniconda3/envs/CATALOG/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/home/julian/miniconda3/envs/CATALOG/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/julian/miniconda3/envs/CATALOG/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2025-01-19 12:04:06,325 INFO    Thread-10 :11544 [wandb_init.py:init():603] run started, returning control to user process
2025-01-19 12:09:08,950 INFO    Thread-10 :11544 [wandb_run.py:finish():1347] finishing run maestria-julian/Ablation_LLMs/vvizkay0
2025-01-19 12:09:08,950 INFO    Thread-10 :11544 [wandb_run.py:_atexit_cleanup():1663] got exitcode: 1
2025-01-19 12:09:08,950 INFO    Thread-10 :11544 [wandb_run.py:_restore():1635] restore
2025-01-19 12:09:08,955 INFO    Thread-10 :11544 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 762
  total_bytes: 762
}

2025-01-19 12:09:09,059 INFO    Thread-10 :11544 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 762
  total_bytes: 762
}

